development:
  host: localhost
  database: mysublime

test:
  host: localhost
  database: msv_test

# set these environment variables on your prod server
production:
  database: sublimevideo
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  hosts:
    - - sublimevideo.member0.mongolayer.com
      - 27017
    - - sublimevideo.member1.mongolayer.com
      - 27017
    - - sublimevideo.member2.mongolayer.com
      - 27017
  use_utc: true
  max_retries_on_connection_failure: 3
  logger: false
