development:
  host: localhost
  database: datasublime-dev
  use_utc: true

test:
  host: localhost
  database: datasublime-test
  use_utc: true

staging:
  uri: <%= ENV['MONGOHQ_URL'] %>
  persist_in_safe_mode: true
  use_utc: true

production:
  uri: <%= ENV['MONGOHQ_URL'] %>
  # persist_in_safe_mode: true
  max_retries_on_connection_failure: 10
  use_utc: true
