development:
  host: localhost
  database: mysublime

test:
  host: localhost
  database: msv_test

# set these environment variables on your prod server
production:
  database: sublimevideo-stats
  username: <%= ENV['MONGOHQ_USERNAME'] %>
  password: <%= ENV['MONGOHQ_PASSWORD'] %>
  host: sublimevideo.member0.mongolayer.com
  port: 27017
  use_utc: true
  max_retries_on_connection_failure: 3
  pool_size: 10
  skip_version_check: true
  logger: false
  # read: :secondary